server_name: mdc_nats2
listen: 0.0.0.0:4222
http_port: 8222

# 1. TLS configuration for client connections
tls {
  cert_file: "/etc/nats/certs/fullchain.pem"
  key_file: "/etc/nats/certs/privkey.pem"
}

# 2. Cluster configuration for server-to-server communication
cluster {
  name: MDC_Cluster
  listen: 0.0.0.0:6222
  routes: [
    nats-route://10.144.144.3:6222,
    nats-route://10.144.144.4:6222
  ]
}

# 3. Leaf node listener
leafnodes {
  listen: 0.0.0.0:7422
  tls {
    cert_file: "/etc/nats/certs/fullchain.pem"
    key_file: "/etc/nats/certs/privkey.pem"
  }
}

# 4. JetStream configuration
jetstream {
	store_dir: /tmp/nats/
	domain: hub
}

# 5. Accounts and Users
accounts {
  # System account for metrics, etc.
  $SYS {
    users = [
       { user: "admin", pass: "$2a$10$Of52tba0beQKL7DviNX6sOSXlnMKKXOJKrimMRutGVl39WPwqIk36" }
    ]
  }

  # Main account for your applications
  CLIENT_ACCOUNT {
    jetstream: enabled
    users = [
      { user: "clientuser", pass: "clIent2026Pw" },
      {
        user: "leafuser",
        pass: "leaf2026Pw",
        permissions: {
          publish: [">"],
          subscribe: [">"]
        }
      }
    ]
  }
}
