server_name: nats_leaf1
listen: 0.0.0.0:4223
http_port: 8222

jetstream {
  store_dir: "/data"
}

# An accounts block is required for the remote to map to.
# This can be empty if no local users are needed.
accounts {
  CLIENT_ACCOUNT {
    jetstream: enabled
    users = [
      { user: "clientuser", pass: "clIent2026Pw" },
      { user: "leafuser", pass: "leaf2026Pw" }
    ]
  }
}

leafnodes {
  remotes = [
    { 
      urls: [ "tls://leafuser:leaf2026Pw@natsgw.marketdispatch.com.au:7422" ]
      account: "CLIENT_ACCOUNT"
      tls {
        insecure: true
      }
    }
  ]
}
