# Create a stream for dispatch commands, kept for 2 days
nats stream add DISPATCH_STREAM --subjects "dispatch.>" --retention limits --max-age 48h ...

# Create a stream for feedback data, kept for 30 days
nats stream add FEEDBACK_STREAM --subjects "feedback.>" --retention limits --max-age 30d ...

# Create a stream for watchdog pings, kept for 1 hour
nats stream add WATCHDOG_STREAM --subjects "watchdog.>" --retention limits --max-age 1h ...